### ISSUE TITLE
Forbidden error when list scenarios 

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/loadimpact-cli#10]
This command returns the project id and organisation OK. 
```loadimpact organization list```

However, when I attempt to list user-scenarios:
```loadimpact user-scenario list```

```
Traceback (most recent call last):
  File "/Users/lewisa29/.pyenv/versions/3.5.1/bin/loadimpact", line 9, in <module>
    load_entry_point('loadimpact-cli==1.0.6', 'console_scripts', 'loadimpact')()
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpactcli/loadimpact_cli.py", line 37, in run_cli
    cli()
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpactcli/userscenario_commands.py", line 50, in list_scenarios
    userscenarios = client.list_user_scenarios(project_id)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpact3/clients.py", line 109, in list_user_scenarios
    return UserScenario.list(self, project_id=project_id)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpact3/resources.py", line 161, in list
    response = client.get(path)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpact3/clients.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpact3/clients.py", line 168, in get
    return self._check_response(response)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/loadimpact3/clients.py", line 231, in _check_response
    msg, response=response)
loadimpact3.exceptions.ForbiddenError: {"error":{"message":"You do not have permission to perform this action.","code":4}} (https://api.loadimpact.com/v3/user-scenarios?project_id=3044266)
```

**Comment by anah** [comment]
@aidylewis Are you sure you are using the right project ID? This works for me:

```
$ loadimpact organization list
3040394 ana@loadimpact.com

$ loadimpact organization projects 3040394
3041000	My first project

$ loadimpact user-scenario list --project_id=3041000
                                                                                                                     
ID:	NAME:
3456911	Script created by CLI
```

**Comment by anah** [comment]
@aidylewis Another thing you might want to check is if you are a member of the project and not just the organization.

**Comment by anah** [comment]
I'm closing this for now, but @aidylewis please let us know if you still experience the issue.
