### ISSUE TITLE
Updating a user scenario with a data store fails 

### ISSUE THREAD

**Issue by alexking** [loadimpact/loadimpact-cli#12]
If you try to update a user scenario that is connected to a data store, 

`loadimpact user-scenario update ###### user-scenarios/app.lua`

It gives this error - 

`{"error":{"message":"You do not have permissions to access one or more of the specified user scenario's data stores","code":5003}}`

Saving it in the web interface works fine. And when I disassociate the datastore with the scenario, it uploads fine via the CLI. I've also tried upload the data store via the `user-scenario create --datastore_file` method, and while it uploads fine initially, updates still result in this error.

Here's the full traceback - 

```Traceback (most recent call last):
  File "/usr/local/bin/loadimpact", line 9, in <module>
    load_entry_point('loadimpact-cli==1.0.6', 'console_scripts', 'loadimpact')()
  File "build/bdist.macosx-10.11-x86_64/egg/loadimpactcli/loadimpact_cli.py", line 37, in run_cli
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.11-x86_64/egg/loadimpactcli/userscenario_commands.py", line 107, in update_scenario
  File "build/bdist.macosx-10.11-x86_64/egg/loadimpactcli/userscenario_commands.py", line 142, in update_user_scenario_script
  File "/usr/local/lib/python2.7/site-packages/loadimpact3/resources.py", line 327, in update_scenario
    return super(UserScenario, self).update(self.client, self.id, data)
  File "/usr/local/lib/python2.7/site-packages/loadimpact3/resources.py", line 142, in update
    headers='', data=data, file_object=file_object)
  File "/usr/local/lib/python2.7/site-packages/loadimpact3/clients.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/loadimpact3/clients.py", line 221, in put
    return self._check_response(response)
  File "/usr/local/lib/python2.7/site-packages/loadimpact3/clients.py", line 231, in _check_response
    msg, response=response)
loadimpact3.exceptions.ForbiddenError: {"error":{"message":"You do not have permissions to access one or more of the specified user scenario's data stores","code":5003}} (https://api.loadimpact.com/v3/user-scenarios/######)
```

**Comment by dbrandt** [comment]
Thank you for reporting this! We'll try to look at it as soon as possible.

**Comment by msbit** [comment]
@dbrandt still experiencing this here.

```
$ loadimpact --version
loadimpact, version 1.0.6
```

**Comment by diego-plan9** [comment]
Thanks for reporting, @msbit (and alexking)! We are currently looking into the issue and preparing an upcoming fix.

**Comment by diego-plan9** [comment]
@alexking and @msbit, could you please check if you are still experiencing the issue? We issued a server-side fix that addresses the problem, and hopefully both cases (1: updating a user scenario that is connected to a data store, and 2: creating a user scenario including a data store on the same command) should work correctly now.

**Comment by msbit** [comment]
@diego-plan9 I can confirm that updating a user scenario similar to the following:

```
loadimpact user-scenario update ${SCENARIO_ID} ${SCENARIO_ID}.lua
```

now works for me.

Not sure about creating a user scenario with an associated data store, that's not something that I've done as part of this project.

Thanks!

**Comment by diego-plan9** [comment]
Thanks for the prompt feedback, @msbit, and glad to know it is working! :+1:

**Comment by diego-plan9** [comment]
Marking the issue as fixed - please feel free to comment back or reopen if needed!
