### ISSUE TITLE
`loadimpact run` exits if the test result request fails

### ISSUE THREAD

**Issue by ppcano** [loadimpact/loadimpact-cli#15]
When running a test, the CLI exits if the request to the test result endpoint `v3/test-runs/XXXX/results` fails.

```
[04:22:57] :	 [Step 5/5] TEST_RUN_ID:
[04:22:57] :	 [Step 5/5] XXXXX
[04:22:57] :	 [Step 5/5] Initializing test ...
[04:24:45] :	 [Step 5/5] TIMESTAMP:                VUs [1]:         reqs/s [1]:      bandwidth [1]:   user load time [1]: failure rate [1]:
.....
[04:42:57]W:	 [Step 5/5] Traceback (most recent call last):
[04:42:57]W:	 [Step 5/5]   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\loadimpact-script.py", line 11, in <module>
[04:42:57]W:	 [Step 5/5]     load_entry_point('loadimpact-cli==1.2.0', 'console_scripts', 'loadimpact')()
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpactcli\loadimpact_cli.py", line 41, in run_cli
[04:42:57]W:	 [Step 5/5]     cli()
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
[04:42:57]W:	 [Step 5/5]     return self.main(*args, **kwargs)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
[04:42:57]W:	 [Step 5/5]     rv = self.invoke(ctx)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
[04:42:57]W:	 [Step 5/5]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
[04:42:57]W:	 [Step 5/5]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
[04:42:57]W:	 [Step 5/5]     return ctx.invoke(self.callback, **ctx.params)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
[04:42:57]W:	 [Step 5/5]     return callback(*args, **kwargs)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpactcli\test_commands.py", line 108, in run_test
[04:42:57]W:	 [Step 5/5]     for i, data in enumerate(stream(poll_rate=3)):
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpact3\resources.py", line 394, in __call__
[04:42:57]W:	 [Step 5/5]     results = TestRunResults.list(self.test_run.client, self.test_run.id, {'ids': ','.join(q)})
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpact3\resources.py", line 200, in list
[04:42:57]W:	 [Step 5/5]     data=json.dumps(data))
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpact3\clients.py", line 54, in wrapper
[04:42:57]W:	 [Step 5/5]     return func(*args, **kwargs)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpact3\clients.py", line 214, in post
[04:42:57]W:	 [Step 5/5]     return self._check_response(response)
[04:42:57]W:	 [Step 5/5]   File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\loadimpact3\clients.py", line 254, in _check_response
[04:42:57]W:	 [Step 5/5]     raise ServerError(msg, response=response)
[04:42:57]W:	 [Step 5/5] loadimpact3.exceptions.ServerError: {"error":{"message":"An unexpected error occurred","code":0}} (https://api.loadimpact.com/v3/test-runs/XXXX/results)
```

**Comment by robingustafsson** [comment]
This has now been fixed in [v1.2.1](https://pypi.python.org/pypi/loadimpact-cli/1.2.1). See https://github.com/loadimpact/loadimpact-cli/blob/develop/CHANGELOG.md.
